"""Request and response models for Flowise API interactions.

This module defines Pydantic models for API requests and responses,
including prediction responses, error responses, and CRUD request models.
"""

from typing import Any

from pydantic import BaseModel, Field, field_validator, model_validator

from fluent_mind_mcp.models.chatflow import ChatflowType
from fluent_mind_mcp.utils.validators import FlowDataValidator


class PredictionResponse(BaseModel):
    """Result from chatflow execution.

    Represents the response from executing a chatflow prediction.

    Attributes:
        text: Response text generated by the chatflow
        question_message_id: Optional question message identifier
        chat_message_id: Optional response message identifier
        session_id: Optional conversation session identifier
    """

    model_config = {"populate_by_name": True}

    text: str = Field(..., min_length=1, description="Response text from chatflow")
    question_message_id: str | None = Field(
        None, alias="questionMessageId", description="Question message identifier"
    )
    chat_message_id: str | None = Field(
        None, alias="chatMessageId", description="Response message identifier"
    )
    session_id: str | None = Field(
        None, alias="sessionId", description="Conversation session identifier"
    )


class ErrorResponse(BaseModel):
    """Standardized error response format.

    Provides consistent error reporting across all API operations.

    Attributes:
        error: Error type or code
        message: User-friendly error description
        details: Optional additional error context
    """

    error: str = Field(..., description="Error type/code")
    message: str = Field(..., description="User-friendly error message")
    details: dict[str, Any] | None = Field(None, description="Additional error context")


class CreateChatflowRequest(BaseModel):
    """Request model for creating a chatflow.

    Defines the structure for chatflow creation requests.

    Attributes:
        name: Chatflow name (1-255 characters)
        type: Chatflow type enum (defaults to CHATFLOW)
        flow_data: JSON string of workflow structure
        deployed: Initial deployment status (defaults to False)
    """

    name: str = Field(..., min_length=1, max_length=255, description="Chatflow name")
    type: ChatflowType = Field(ChatflowType.CHATFLOW, description="Chatflow type")
    flow_data: str = Field(..., min_length=1, description="JSON string of workflow")
    deployed: bool = Field(False, description="Initial deployment status")

    @field_validator("flow_data")
    @classmethod
    def validate_flow_data_structure(cls, v: str) -> str:
        """Validate flow_data structure, size, and JSON format.

        WHY: Uses centralized FlowDataValidator to ensure consistent validation
             across all parts of the system. This eliminates code duplication
             and makes validation logic easier to maintain.
        """
        validator = FlowDataValidator()
        return validator.validate_for_pydantic(v)


class UpdateChatflowRequest(BaseModel):
    """Request model for updating a chatflow.

    Defines the structure for chatflow update requests.
    At least one optional field must be provided.

    Attributes:
        chatflow_id: Chatflow identifier to update
        name: Optional new name (1-255 characters)
        flow_data: Optional new workflow structure
        deployed: Optional new deployment status
    """

    chatflow_id: str = Field(..., min_length=1, description="Chatflow to update")
    name: str | None = Field(None, min_length=1, max_length=255, description="New name")
    flow_data: str | None = Field(None, min_length=1, description="New workflow structure")
    deployed: bool | None = Field(None, description="New deployment status")

    @field_validator("flow_data")
    @classmethod
    def validate_flow_data_structure(cls, v: str | None) -> str | None:
        """Validate flow_data structure, size, and JSON format if provided.

        WHY: Uses centralized FlowDataValidator to ensure consistent validation
             across all parts of the system. This eliminates code duplication
             and makes validation logic easier to maintain.
        """
        if v is not None:
            validator = FlowDataValidator()
            return validator.validate_for_pydantic(v)
        return v

    @model_validator(mode="after")
    def validate_at_least_one_field(self) -> "UpdateChatflowRequest":
        """Validate that at least one optional field is provided.

        WHY: Update requests must specify at least one field to update.
        """
        if self.name is None and self.flow_data is None and self.deployed is None:
            raise ValueError("At least one of name, flow_data, or deployed must be provided")
        return self
